### ISSUE TITLE
 how to Save Posation Scroll horizontal List in scroll top?

### ISSUE THREAD

**Issue by sepiddezh** [lisawray/groupie#164]
Hi
how to Save Posation Scroll horizontal List in scroll top?
not save posation horizontal in restore scroll verticall

Like: 
https://github.com/jeffreyliu8/Nested-RecyclerView

**Comment by sepiddezh** [comment]
please help me

**Comment by lisawray** [comment]
I know this is kind of lame answer, but strictly speaking, the horizontal scroll position is not exactly known because a RV only knows about the size of the items that are in it, not the items that have come before or after.  

You can however save the first visible item, which is probably close enough: 
LinearLayoutManager.findFirstVisibleItemPosition();

You can save this value whenever you like -- by setting an OnScrollListener on your RV, for example, or by overriding Item.unbind(viewholder) and capturing the position then.
