### ISSUE TITLE
MVVM and Groupie - Where to instantiate/cache Items?

### ISSUE THREAD

**Issue by bemusementpark** [lisawray/groupie#194]
`Item` has view-level responsibilities. At the least we create Views from layout `id`s, at most we have intricate model->view "glue" code.

In MVVM the VM does not modify or have a direct reference to the View.

So if we have a list of colors in our `VM`, `List<Int>` that we want to turn into `ColorItem`s and show in our `View`, then I would be tempted to put a `fun colors(): rx.Observable<List<Int>>` in our VM, and map to `ColorItem` in the View: `vm.colors().map(::ColorItem)`. This has the unintended consequence of creating a `ColorItem` for every item in the emitted `List` from `colors()`, even though this may be unnecessary, as the same old `Item`s from before would suffice.

It's awkward to put Item-caching logic in the view as it can be complex and it's not necessarily unit-testable, but it's not a concern we necessarily want our VM to deal with.

Where should we create `Item`s and how can we cache them to save recreating every `Item` every time a fine-grained change occurs?

**Comment by lisawray** [comment]
I've been working with a ViewModel and Rx lately, and what I tend to do is have the ViewModel construct the items or groups.  I usually have a method `ViewModel.getGroups(): Observable<List<Group>>` which my view subscribes to.  In this case, it would be something like:

```
fun getGroups(): Observable<List<Group>> = colors().map { it.map { ColorItem(it) } }

```

In `onNext()` in my view, I call `GroupAdapter.update()` or `GroupAdapter.updateAsync()` (from the latest alpha).

Your example is all on the main thread, but using Rx also allows me to construct my list of items or groups in the background.  In practice, it's allowed me to create extremely complex screens where the contents depend on many inputs and update seamlessly using diffs and payloads.  I'm a big fan of Rx :)

You can also write unit tests which assert against the contents of `getGroups()` given different inputs.

Does this answer your question?  I'm not sure what exactly about new object creation concerns you.

**Comment by bemusementpark** [comment]
> You can also write unit tests which assert against the contents of getGroups() given different inputs.

I was thinking that as an `Item` inflates a specific `View` and populates it, it is essentially View-Layer, and not VM layer. It drags the VM that created it into View-layer responsibility. This prevents us from say creating separate modules for VM and V concerns. That is without putting this logic into the View itself, which has it's own issues.

What do you test on?
do you test the model backing the `Item` is valid?
do you mock `View`/`Binding`s and check the right properties are set?
It seems like View and data requirements/tests may get blurred here.

> Does this answer your question? I'm not sure what exactly about new object creation concerns you.

Using `DiffUtil`, we need to allocate `listA : List<Int>` and `listB : List<Int>`. But with Groupie we will often allocate an additional `List<ColorItem>` for each.

Perhaps I'm a bit paranoid to be concerned about a linear increase in memory consumption. I was thinking about caching certain items, but it's probably more trouble than it's worth and makes payload-changes more difficult.

**Comment by lisawray** [comment]
I do see that you could strictly consider the Item part of the View layer.  To avoid that, the library would have to split the Item class into two -- for every type a "model" (ColorItem) and "view" (ColorView).  If you absolutely don't want the model to know about the view, then you'd have to have a type registry to associate the two for the adapter, or maybe use annotations and generate it.  In this case, I feel simplicity beats out architectural purity.  I'm aware not everyone has the same opinion :) 

The unit tests I write usually assert that my list contains the correct number, order, and types of groups (or items).  For example, "When user is an admin, then they see the member requests section."  

Unless your own model objects (Color, etc) are very large and you're making new copies of those each time you create an Item, a new list of Item objects really shouldn't take up much memory.  So I'm not sure I see an Item cache as a general purpose need.  In fact, I can see it creating a lot of confusion.  

I'm open to continuing this discussion, but I think I'd like to see a concrete problem to solve first rather than just the hypothetical.

**Comment by bemusementpark** [comment]
That clears it up, Thanks Lisa!
