### ISSUE TITLE
Question: Header view with items within.

### ISSUE THREAD

**Issue by iandreyshev** [lisawray/groupie#200]
Is this possible to create header view with childs within?
[my art](https://pp.userapi.com/c849020/v849020167/2f363/46a2b5aLc74.jpg)

**Comment by tkindy** [comment]
I'm not totally sure if I'm interpreting your drawing correctly, but it looks like you have a full-screen view with an element called 'Parent' at the top with the rest of the list items below it.

Does the parent (a) stay locked at the top of the screen when you scroll, or does it (b) scroll with the rest of the list?

If it's (a), you could add a separate component above the `RecyclerView` in your layout. In this case, Groupie would have nothing to do with managing the parent.

If it's (b), the parent could be defined as a [`HeaderItem`](https://github.com/lisawray/groupie/blob/44918281d800eaf0be5f4c697e3b2fe10c0b7bd5/example/src/main/java/com/xwray/groupie/example/MainActivity.kt#L106) or a different kind of `Item` that you manually place before all the other items before submitting the list to the adapter.

**Comment by tkindy** [comment]
Take a look at [`ExpandableGroup`](https://github.com/lisawray/groupie/blob/master/library/src/main/java/com/xwray/groupie/ExpandableGroup.java), that might serve your use case.

**Comment by iandreyshev** [comment]
@tkindy 
Parent is HeaderItem but I want to create one view for HeaderItem and its childs to create one CardView for  them. I want to have one common shadow for HeaderItem and Items

**Comment by tkindy** [comment]
Hmm isn't that just the `RecyclerView` itself? It contains the `HeaderItem` plus each of the `CardView`s in a common UI element. I might still be understanding the design you're shooting for.

**Comment by iandreyshev** [comment]
@tkindy 
Like this: https://github.com/kitek/android-rv-one-cardview
But I want several cards with header and they will be expandable

**Comment by lisawray** [comment]
Sorry this is so late.  @iandreyshev , unfortunately the shadow of a CardView is something that's hard to imitate.  In order to split its contents into multiple items, they'd have to be different views in the RV, and then they can't be inside a CardView anymore.  

You could experiment with drawing a drop shadow in your ItemDecoration to mimic the appearance of a card. If you do, I'd love to see the code and maybe add an example. This is something I get asked about a lot and usually just tell people, "It's complicated ..."

Closing for now since this isn't a Groupie-specific issue.

**Comment by tskulbru** [comment]
Just wanted to chime in here as I had a similar question regarding cardviews in recyclerview. Itemdecoration is the way to go for this, take a look at https://github.com/ajarl/item-decoration-sample @iandreyshev

**Comment by iandreyshev** [comment]
@tskulbru this is nice solution, but only for API level >= 21
