### ISSUE TITLE
androidx.constraintlayout.widget.ConstraintLayout cannot be cast to android.widget.FrameLayout

### ISSUE THREAD

**Issue by Turalllb** [lisawray/groupie#426]
release 2.8.0 and 2.9.0

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/28982210/163012698-c2bec0ac-f03c-4615-ad46-ae8ee6837dd8.png">

included
<img width="606" alt="image" src="https://user-images.githubusercontent.com/28982210/163012870-ea559822-3e6e-43a9-a7e9-9c8211af13a8.png">

root 
<img width="520" alt="image" src="https://user-images.githubusercontent.com/28982210/163008739-5d9f49ff-9ded-4c27-b578-32c83588c8ed.png">

I don’t know how this library works at all, but I see such a crash, colleagues confirmed that they also had such crashes in other places of the application. The bottom line is that in the root xml we try to include partial_card_title , it lies in the Constraint Layout , but the FrameLayout itself. Why does the bind function try to cast these two types?

**Comment by Zhuinden** [comment]
The library doesn't try to cast, your `PartialCardTitleBinding.bind()` might. You're supposed to add an ID to the `<include` to access it through the binding of the root, and you're also supposed to `bind()` using the binding for the layout and not the included layout (I cannot tell its name, as it was not provided).

So I'll say it should be `RootBinding.bind(root).includedPartialCardTitle` (if using `android:id="@+id/includedPartialCardTitle` on the `<include`) because this is how ViewBinding works, regardless of what Groupie is doing.

**Comment by Turalllb** [comment]
@Zhuinden Thanks for the answer, I really want to understand you, but so far I can’t, I should read the documentation, but first I would like to solve the problem with your help. I have updated the question, could you please try again, thanks

**Comment by Turalllb** [comment]
OO seems to understand, I'll set the id for include and try to bind it

**Comment by Turalllb** [comment]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/28982210/163014256-7a795e8e-8477-4600-bb2a-c88429e1b121.png">
 I figured out that to access nested root , I just have to set the id

thanks for the help
