### ISSUE TITLE
Q: Show/Hide Section with CarouselItem

### ISSUE THREAD

**Issue by andhie** [lisawray/groupie#86]
I have a `Section`, a section header and a CarouselItem. 
I want this section to hide when CarouselItem is empty and show when Carousel has items.
How do i setup this behavior?

```java
// onCreate
Section section = new Section(new HeaderItem("Header"));
section.setHideWhenEmpty(true);
CarouselItem carousel = new CarouselItem();
section.add(carousel);

// after network response 
carousel.addAll(cardItemList);
carousel.notifyChange(); // to trigger getItemCount()
```

I modify the CarouselItem to return 0 or 1 based on the carousel adapter.
```java
public int getItemCount() {
    return (adapter == null || adapter.getItemCount() == 0) ? 0 : 1;
}
```

Result: The Carousel is displayed but section header is still hidden.

**Comment by lisawray** [comment]
You want to set an AdapterDataObserver on the CarouselItem's adapter.  This will let you know when the carousel's contents change. When the carousel changes to empty or not empty, you need to notify the parent. 

The main problem right now is that although you've changed what the method `CarouselItem.getItemCount()` would potentially return, no one is calling it, because no one knows the contents of the main list have changed.

I would extend the Section instead and override `isEmpty()`.  When the carousel's state changes, call `Section.refreshEmptyState`.

**Comment by andhie** [comment]
I think something is missing. the code gist implements the `Section#add` and `Section#remove` approach. the header always appears

https://gist.github.com/andhie/a6d1841473ecd9586c4643f15c2a0648

**Comment by lisawray** [comment]
Hey @andhie, I added a PR adding a carousel section that hides itself when there are no carousel contents. I didn't get to debug your gist but I used a different approach, making a very simple Group wrapper (CarouselGroup) which reports a single CarouselItem added or removed.  Placing this group inside a Section with `setHideWhenEmpty` produces the desired result.

https://github.com/lisawray/groupie/pull/97
