### ISSUE TITLE
Does your library support subheaders?

### ISSUE THREAD

**Issue by sotrh** [lisawray/groupie#99]
I need to have a header separated list that can have subheaders. I have a list of varying types. One of these types need to be further grouped by subject. Is there any way to do this with this library?

**Comment by lisawray** [comment]
Definitely! I imagine you mean something like:

* Dogs
    - Large
        1. Golden retriever
        2. Standard poodle
        3. Great Dane
    - Small
        1. Daschshund
        2. Pit bull
    - Tiny
        1. Chihuahua
* Cats
    1. Persian
    2. Siamese

You have many implementation options, but something like this seems easiest to me:

```
val catSection = Section(HeaderItem("Cats");
cats.forEach {
    catSection.add(PetItem(it))
} 
val dogSection = Section(HeaderItem("Dogs");
dogSizes.forEach {
    val sizeSection = Section(SubHeaderItem(it.name()));
    dogSizes.dogs.forEach {
        sizeSection.add(PetItem(it))
    }
}
groupAdapter.add(dogSection)
groupAdapter.add(catSection)
```

If you want to expand and collapse the groups, then make all the headers extend `ExpandableItem` and instead of `Section`, use `ExpandableGroup`. You can nest them as deep as you like.

You can use different view types for headers, subheaders, and their children to make them look different. Or if you want to use an ItemDecoration to distinguish them instead, you can play with Item.setExtras() to set arbitrary flags on viewholders of the same type (like nesting depth for indents).

Happy to elaborate if you have more questions!

**Comment by sotrh** [comment]
Awesome, that's exactly what I needed :)
